e2022.05.17/config/routes.rb
Rails.application.routes.draw do
  get 'admins/index'
  get 'admins', to: 'admins#index'

  get 'users/index'
  patch 'users/:id', to: 'users#update', as: 'users'

  devise_for :users, controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions'
      }
  resources :stories
  root 'stories#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

e2022.05.17/app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">PicStory</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% unless user_signed_in? %>
      <ul class="nav navbar-nav">
        <li><%= link_to "Register", new_user_registration_path %></li>
        <li><%= link_to "Sign in", new_user_session_path %></li>
      </ul>
      <% end %>
      <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-user-circle-o" style="font-size:24px""></i>
            <span class="caret"></span>
          </a>
          <!-- ¡Pending implementation! Should work toggling between sign_in and sign_out -->
          <ul class="dropdown-menu">
            <li><%=link_to 'Create PicStory', new_story_path %></li>
            <li><%=link_to 'My PicStories', users_index_path %></li>
            <li><a href="#">'My Profile'</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
      <% end %>
    </div>
  </div>
</nav>