e2022.05.09/config/routes.rb
Rails.application.routes.draw do
  get 'buildings/index'
  get 'buildings/create'
  get 'buildings/show'
  get 'buildings/edit'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
    resources :buildings do
      resources :apartments
    end
  # Defines the root path route ("/")
  # root "articles#index"
    root "buildings#index"
end

e2022.05.09/app/models/apartment.rb
class Apartment < ApplicationRecord
  belongs_to :building    
end

e2022.05.09/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

e2022.05.09/app/models/building.rb
class Building < ApplicationRecord
    has_many :apartments, dependent: :destroy
    accepts_nested_attributes_for :apartments
    allow_destroy: true, reject_if: proc { |attributes| attributes['number'].blank? }

    def to_s
        name    
    end


end

e2022.05.09/app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
    def index
        @building = Building.find params[:building_id]
        @apartments = @building.apartments
    end

    def new
        @building = Building.find params[:building_id]
        @apartment = Apartment.new
    end

    def create
        @building = Building.find params[:building_id]
        @apartment = Apartment.new(apartment_params)
        @apartment.building = @building             
        respond_to do |format|
            if @apartment.save
                format.html { redirect_to building_apartment_path(@building, @apartment), notice: 'El departamento fue registrado con éxito.' }
            else
                format.html { render :new }
        end
    end

    def show
        @building = Building.find params[:building_id]
        @apartment = Apartment.find(params[:id])
    end

    def edit
        @building = Building.find params[:building_id]
        @apartment = Apartment.find(params[:id])
    end

    def update
        @building = Building.find params[:building_id]
        @apartment = Apartment.find params[:id]
        respond_to do |format|
            if @apartment.update(apartment_params.merge(building: @building))#             Se añade el building que se obtuvo en la llamada a find_building
                format.html { redirect_to building_apartment_path(@building, @apartment), notice: 'El departamento fue actualizado correctamente.' }
                else
                format.html { render :edit }
            end
        end
    end
    
    def destroy
        @apartment = Apartment.find params[:id]
        @apartment.destroy
        respond_to do |format|
            format.html { redirect_to building_apartments_url, notice: 'El departamento fue borrado exitosamente.' }
        end
    end

end

private
    def apartment_params
        params.require(:apartment).permit(:number)
    end
end

e2022.05.09/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

e2022.05.09/app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  def index
    @buildings = Building.all.reverse_order
  end

  def new
    @building = Building.new
    @building.apartments.build
  end

  def create
    @building = Building.new(building_params)
    if @building.save
      redirect_to building_path(@building)
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  private
    def building_params
      params.require(:building).permit(:name, apartments_attributes:[:id, :number, :_destroy])
    end
end

e2022.05.09/app/helpers/apartments_helper.rb
module ApartmentsHelper
end

e2022.05.09/app/helpers/application_helper.rb
module ApplicationHelper
end

e2022.05.09/app/helpers/buildings_helper.rb
module BuildingsHelper
end

e2022.05.09/app/views/buildings/_form.html.erb
<br>
<p>Información Edifico</p>
    <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name %>
    </div>
<br>
<p>Información Departamentos</p>
    <%= form.fields_for :apartments do |apartment_form| %>
        <%= apartment_form.label :number %>
        <%= apartment_form.text_field :number %>
        <%= apartment_form.label :sale_price %>
        <%= apartment_form.text_field :sale_price %>
    <% end %>

e2022.05.09/app/views/buildings/create.html.erb
<h1>Buildings#create</h1>
<p>Find me in app/views/buildings/create.html.erb</p>

e2022.05.09/app/views/buildings/edit.html.erb
<h1>Buildings#edit</h1>
<p>Find me in app/views/buildings/edit.html.erb</p>

e2022.05.09/app/views/buildings/index.html.erb
<h1>Buildings#index</h1>
<p>Find me in app/views/buildings/index.html.erb</p>

e2022.05.09/app/views/buildings/new.html.erb
<br>
<h1>Nuevo Departamento</h1>
<br>
<%= render 'form', apartment: @building %>
<%= link_to 'Volver', buildings_path(@building) %>

e2022.05.09/app/views/buildings/show.html.erb
<h1>Buildings#show</h1>
<p>Find me in app/views/buildings/show.html.erb</p>